lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  api_platform: # Ajout
    check_path: /api/login_check # Ajout
    username_path: username # Ajout
    password_path: password # Ajout
